bg_source: LEFT
gamma: 0.7
height: 640
n_prompt: bad quality, worse quality
num_frames: 81
num_step: 25
relight_prompt: a man dancing, neon light
save_path: ./test_out/man_taking_notes_12
seed: 666
strength: 0.3
text_guide_scale: 2
vdm_prompt: a man dancing,
video_path:./man_taking_notes_12/downsized_video.mp4
width: 480
