bg_source: TOP
fps: 24
gamma: 0.7
height: 848
n_prompt: bad quality, worse quality
num_frames: 81
num_step: 10
relight_prompt: sunset lighting
save_path: ./
seed: 42
strength: 0.3
text_guide_scale: 2
vdm_prompt: a sea gull standing on a pole
video_path: ./
width: 480
