n_prompt: "bad quality, worse quality"
vdm_prompt: "a woman holding a phone and a cup of coffee"
relight_prompt: "green aurora light"
video_path: "demo/woman_holding_a_coffee_1.mp4"
bg_source: "LEFT"  ## LEFT, RIGHT, BOTTOM, TOP
save_path: "output"

width: 480
height: 640
num_frames: 49
strength: 0.4
gamma: 0.7
num_step: 10
text_guide_scale: 2
seed: 422
